version: '2'
services:
  front:
    build: ./front
    volumes:
      - ./front/src:/app
      - ./front/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"     # Dist
      - "8000:8000" # Dev
    depends_on:
      - api

  api:
    build: ./api
    command: contact_us
    volumes:
      - ./api/src:/go/src/github.com/LastZactionHero/contact_us/
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
    - './api/.env'

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: